### ISSUE TITLE
Router5 doesn't recognize initial state if url has params

### ISSUE THREAD

**Issue by Crazy-Ivan** [router5/router5#15]
I have problem with url containing parameters. For example if I added a node with path "/something/:id" and in application I navigated to this particular path - everything works. If from this point (http://example.com/#/something/321")  i will try to reload app, router will init default route (which is in my case 404 page). I guess this is not proper behavior. From my point of view, url http://example.com/#/something/321" should match to "/something/:id".

**Comment by troch** [comment]
I just checked on the provided online example: http://router5.github.io/docs/with-react.html#/inbox/message/2. I also ran some further tests locally: they all pass. I don't see what would cause this. How are you calling `.start()`?

**Comment by Crazy-Ivan** [comment]
i have created a service which just create an instance of router5, setup it and export. 
Then I include this service into few react components, each of can setup new routes. 
At the end (when all react components are initialized) I fired .start(). 

I have debug it and i'm 100% sure that all routs are defined. They are in rootNode.children property before i call start();

Any other routes which i defined in the same place worked. The only one with param doesn't.
This route is defined in the root level. 

router.addNode('something', 'something/:id');

**Comment by troch** [comment]
What is you do `router.addNode('something', '/something/:id');`? ('/' in front of something)

**Comment by Crazy-Ivan** [comment]
This is what I in fact do. In comment i made a mistake.
```
router.addNode('something', '/something/:id');
```

**Comment by troch** [comment]
I have just released `0.4.0`.

When you start, can you try the following:

```javascript
// Log location
console.log(router.getLocation());

router.start(function (err, state) {
    // Log any err or resolved state
    console.log(err, state);
});

**Comment by Crazy-Ivan** [comment]
I have updated the lib, however still the same issue. 
console log give me what i have expected. 
'/something/4'
null
{ my default state }

**Comment by troch** [comment]
It is reading the URL properly from . What version of router5 are you using?

**Comment by Crazy-Ivan** [comment]
![image](https://cloud.githubusercontent.com/assets/4831814/8961883/08f0573e-3618-11e5-86eb-673585332b32.png)

**Comment by troch** [comment]
I need to go so I'll investigate further later tonight.

**Comment by Crazy-Ivan** [comment]
ok thanks

**Comment by Crazy-Ivan** [comment]
I found it. The problem was/is in route-node.js. There is a loop which looking first match. In my case i have 4 routes defined. One of them is just '\' which I called 'home'; 
```
router.addNode('home', '\');
```

The method founds that path '/details/4' match to my 'home' node (which is not correct)

**Comment by troch** [comment]
Ah! It has been raised and fixed previously (#8). If you are using the latest version, then I have to look into the sorting of routes again.

**Comment by troch** [comment]
@Crazy-Ivan I have fixed it => v0.4.1 has been released and contain the fix. Thank you for your patience!

**Comment by Crazy-Ivan** [comment]
:+1:

**Comment by b3ni** [comment]
Still the problem with the parameters in the urls.

I have the following router configuration:

const routes = [
     {name: 'users', path: '/ users /'},
     {name: 'users.new', path: '/ new /'},
     {name: 'users.detail', path: '/: id <[0-9a-f -] {36}> /'},
];

const router = createRouter (routes, {allowNotFound: true})
     .usePlugin (browserPlugin ({useHash: false}));


I can navigate correctly to the detail of a user, but when I reload the page I get 404.

I am using router5 with react-redux (middleware option), versions:

"router5": "^ 6.3.0"
"react-router5": "^ 6.0.4"
"redux-router5": "^ 6.0.2"

**Comment by b3ni** [comment]
This code works perfectly.

```
const routes = [
     {name: 'users', path: '/users/'},
     {name: 'users.new', path: '/new/'},
     {name: 'users__detail', path: '/users/:id<[0-9a-f -] {36}>/'},
];
```
