### ISSUE TITLE
Browser plugin removes trailing slash before adding hash when `useHash` is enabled

### ISSUE THREAD

**Issue by matthewgertner** [router5/router5#261]
We are deploying our app on a subdirectory of our webserver, so instead of www.example.com it runs at www.example.com/subdirectory/. We're using the `useHash` option of the browser plugin, and for some reason the URLs are being rendered as www.example.com/subdirectory#/ instead of the expected www.example.com/subdirectory/#/. This causes any relative URLs (e.g. `img/logo.png`) to resolve wrongly (in this case to www.example.com/img/logo/png, removing the `subdirectory` portion of the path).

The problem goes away if we set the `base` option of the browser plugin to `/subdirectory/`, but I'm still wondering if this is a bug or by design.

**Comment by troch** [comment]
I'm currently refactoring route-node (dependency of router5), so will have a look.

**Comment by troch** [comment]
Fixed

**Comment by scniro** [comment]
@troch this is still happening to me. The link from your comment on Apr 19 is dead... Any ideas?
