### ISSUE TITLE
canActivate() not get called for routes within a children array

### ISSUE THREAD

**Issue by iotch** [router5/router5#67]
Hello.
`canActivate()` gets ignored for the following config:
```js
const routes = [
    {
        name: 'parent',
        path: '/parent',
    },
    {
        name: 'parent.childA',
        path: '/childA',
    },
    {
        name: 'parent.childB',
        path: '/childB',
        children: [
            {
                name: 'subchild',
                path: '/subchild',
                canActivate: function() {
                    return new Promise(function(resolve) {
                        setTimeout(resolve, 3000);
                    });
                }
            }
        ]
    },
]
```

Is this an expected behaviour?
Thanks.

**Comment by troch** [comment]
This has been fixed in [route-node](/troch/route-node). The issue was not that your callback wasn't called, but it wasn't registered for nested routes specified using `children`. router5 has not been bumped yet, I'll do that tomorrow. In the mean time, you can update / re-install router5 and the latest version of route-node should then be applied.

**Comment by iotch** [comment]
Still does not work for me with route-node 1.4.3 installed...
